import Head from 'next/head'

import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { FaTwitter, FaGithub, FaLinkedin } from 'react-icons/fa';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
       <nav className={styles.navbar}>
      <ul className={styles.icons}>
        <li>
          <a href="https://twitter.com">
            <FaTwitter className={styles.icon} />
          </a>
        </li>
        <li>
          <a href="https://github.com">
            <FaGithub className={styles.icon} />
          </a>
        </li>
        <li>
          <a href="https://linkedin.com">
            <FaLinkedin className={styles.icon} />
          </a>
        </li>
      </ul>
    </nav>
      <Head className="head">
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Hey , This is vikash 
      </main>
    </div>
  )
}
